apiVersion: apps/v1
kind: Deployment
metadata:
  name: director
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: bbelliveau/director:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: director
  namespace: default
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80